name: Daily Docker Build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run update.sh
      run: bash update.sh
      continue-on-error: true

    - name: Build and push Docker image
      if: ${{ success() }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          tsfreddie/ai00_rwkv_docker:latest
          tsfreddie/ai00_rwkv_docker:${{ env.latest_release }}
